### ISSUE TITLE
Initializing DailyMotion API via SDK to make API calls

### ISSUE THREAD

**Issue by codemanimal** [codemanimal/Stream_Guide#1]
What am I trying to do:
Load DailyMotion SDK so that I can make API calls from my server

Detailed description:
DailyMotion recommended syntax for initializing the API (https://developer.dailymotion.com/tools/sdks#sdk-javascript-methods):
```
<script src="http://api.dmcdn.net/all.js"></script>
<script>
    DM.init({
        apiKey: 'YOUR API KEY',
        status: true, // check login status
        cookie: true // enable cookies to allow the server to access the session
    });
</script>
```

I should then be able to make API calls using 'DM.api()' as per the API docs in the link above, but my server is saying that 'DM' is not defined.

Here is my server code:
```
DM.init({
    apiKey: 'e542a26cabdfbdec523c',
    status: true, // check login status
    cookie: true // enable cookies to allow the server to access the session
});

DM.api('/videos',
  { fields: 'audience,bookmarks_total,broadcasting,channel,country,description,duration_formatted,embed_html,end_time,explicit,id,language,metadata_credit_actors,metadata_credit_director,metadata_genre,metadata_original_title,onair,owner.url,poster_url,recurrence,start_time,status,tags,thumbnail_url,title,url,views_last_day,views_last_hour,views_last_month,views_last_week,views_total', 
    flags: 'live', sort: 'live-audience', limit: 100
  },
  function(error, response, body) {
    var results = body.data;
    res.send(results);
});
```

@h4w5 @WilliamfShaw @bigtone1284

**Comment by bigtone1284** [comment]
@codemanimal can you please push you most recent work to your repo on github?  Thanks.

**Comment by h4w5** [comment]
@codemanimal you must do as @bigtone1284 says. but also your example is code that is meant for use in the browser, while your problem states that you are running your code on the server. their library defines the `DM` object. to run this code on your server you need to maybe include their library via your `package.json` if it exists, and then require the given module, eg:

```javascript
DM = require('daily-motion');
```

**Comment by bigtone1284** [comment]
@harimohanraj89

**Comment by bigtone1284** [comment]
taken @harimohanraj89 @WilliamfShaw

**Comment by codemanimal** [comment]
Re-opening this issue - still cannot make calls to DM API from my server

**Comment by bigtone1284** [comment]
taken
 @harimohanraj89 @WilliamfShaw @DrRobotmck @bigtone1284
